# Generated by Django 4.1.13 on 2023-12-10 08:02

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='network/static/profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_info',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_list', django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), size=None)),
                ('balance_list', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
