# Generated by Django 4.1.13 on 2023-12-12 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0004_alter_data_balance_list_alter_data_date_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='balance_list',
        ),
        migrations.RemoveField(
            model_name='data',
            name='date_list',
        ),
    ]
