# Generated by Django 4.1.13 on 2023-12-13 16:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0005_remove_data_balance_list_remove_data_date_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='balance_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='data',
            name='date_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DateField(), blank=True, null=True, size=None),
        ),
    ]
