# Generated by Django 4.1.13 on 2023-12-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0006_data_balance_list_data_date_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
