# Generated by Django 4.1.13 on 2023-12-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interface', '0007_data_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='balance_list',
        ),
        migrations.RemoveField(
            model_name='data',
            name='date_list',
        ),
    ]
